version: "3"
services:
  database:
    image: mysql:5.7
    volumes:
      - mysql_project:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_USER: manali
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: my_db

  drupal:
    image: drupal:latest
    restart: always
    depends_on:
      - database
    ports:
      -8082:80
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: manali
      POSTGRES_HOST: database
      POSTGRES_PASSWORD: redhat
    volumes:
      - drupal_storage:/var/www/html
    
volumes:
  mysql_project:
  drupal_storage:
